# Root where to look for the libraries.
# Defaults to /usr/lib if not specified.
root: /usr/lib

# Look into $root (defined above) for the following patterns
# and grab those binaries
patterns:
  - libasan
  - libatomic
  - libgcc
  - libgomp
  - libssp
  - libstc++

# If a any pattern above matches, grab the whole package
# it belongs to (not just the very library bin).
patterns_packages: true

# Grab whole packages with the entire content
packages:
